name: Create Release
on:
  workflow_dispatch
jobs:
  Create-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Build and release
        uses: philippe-patenaude/lpak@v1.1.8
        with:
          RELEASE_VERSION: 1.0.0
          GAME_NAME: deep-stratum-defense
